---
# yamllint configuration
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Allow longer lines (default is 80)
  line-length:
    max: 120
    level: warning

  # Allow document start markers to be optional
  document-start: disable

  # Allow indentation in some contexts
  indentation:
    spaces: 2
    indent-sequences: true

  # Allow truthy values like 'on', 'off', 'yes', 'no'
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
    check-keys: false
