"""Resolve every world's Modrinth mod specs into a pinned lock file.

Usage: update-mods.py SPEC_JSON LOCK_JSON

SPEC_JSON (generated by Nix from `my.minecraft-servers`' `worlds`, see minecraft-servers.nix):
  {
    "availableGameVersions": [...],  # every game version nix-minecraft can build a server for
    "worlds": {
      "<world>": {
        "loader": "fabric",
        "gameVersion": null | "1.21.8",  # null: newest version every mod supports
        "mods": { "<modrinth slug>": { "channel": "release" | "beta" | "alpha" } }
      }
    }
  }

LOCK_JSON (read, then rewritten in place):
  { "<world>": { "gameVersion": "...", "mods": { "<slug>": { "channel", "version", "url", "sha512" } } } }

The game version is chosen FROM the mods rather than the other way round, so a nix-minecraft bump
can never move a world onto a Minecraft release its mods don't support yet. An unpinned world only
ever moves forward: if the newest version every mod supports is older than the one already locked
(e.g. a newly added mod hasn't caught up), this fails rather than downgrade the world.
"""

import json
import sys
import urllib.parse
import urllib.request

API = "https://api.modrinth.com/v2"
USER_AGENT = "OscarMarshall/dotfiles (update-minecraft-mods)"
# Seconds per request - a hung connection would otherwise stall the scheduled workflow indefinitely.
TIMEOUT = 30

# Each channel also accepts everything more stable than itself.
CHANNELS = {
    "release": {"release"},
    "beta": {"release", "beta"},
    "alpha": {"release", "beta", "alpha"},
}


def get(path, **params):
    query = urllib.parse.urlencode({key: json.dumps(value) for key, value in params.items()})
    request = urllib.request.Request(f"{API}{path}?{query}", headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=TIMEOUT) as response:
        return json.load(response)


def pick(versions, game_version, channel):
    """Newest version of a mod built for `game_version` on an allowed channel, or None."""
    allowed = CHANNELS[channel]
    return next(
        (
            version
            for version in versions
            if game_version in version["game_versions"] and version["version_type"] in allowed
        ),
        None,
    )


def lock_entry(version, channel):
    file = next((file for file in version["files"] if file.get("primary")), version["files"][0])
    # `channel` is recorded so Nix can tell a lock resolved under a different channel is stale.
    return {"channel": channel, "sha512": file["hashes"]["sha512"], "url": file["url"], "version": version["version_number"]}


def resolve_world(name, world, available, release_order, locked):
    mods = world["mods"]
    versions = {
        slug: sorted(
            get(f"/project/{slug}/version", loaders=[world["loader"]]),
            key=lambda version: version["date_published"],
            reverse=True,
        )
        for slug in mods
    }

    def picks_for(game_version):
        picks = {slug: pick(versions[slug], game_version, spec["channel"]) for slug, spec in mods.items()}
        return picks if all(picks.values()) else None

    if world["gameVersion"] is not None:
        game_version = world["gameVersion"]
        picks = picks_for(game_version)
        if picks is None:
            missing = [slug for slug, spec in mods.items() if not pick(versions[slug], game_version, spec["channel"])]
            sys.exit(f"{name}: no {game_version} build of {', '.join(missing)} on an allowed channel")
    else:
        candidates = [version for version in release_order if version in available]
        game_version, picks = next(
            ((version, picks) for version in candidates if (picks := picks_for(version))), (None, None)
        )
        if game_version is None:
            sys.exit(f"{name}: no Minecraft release is supported by every mod")
        current = locked.get("gameVersion")
        if current in release_order and release_order.index(game_version) > release_order.index(current):
            sys.exit(
                f"{name}: newest version every mod supports is {game_version}, older than the locked {current} -"
                " refusing to downgrade the world (pin `gameVersion` or drop the lagging mod)"
            )

    project_ids = {version["project_id"] for version in picks.values()}
    for slug, version in picks.items():
        for dependency in version["dependencies"]:
            if dependency["dependency_type"] == "required" and dependency["project_id"] not in project_ids:
                print(f"warning: {name}: {slug} requires Modrinth project {dependency['project_id']} (fine if bundled in its jar)", file=sys.stderr)

    return {"gameVersion": game_version, "mods": {slug: lock_entry(version, mods[slug]["channel"]) for slug, version in picks.items()}}


def main(spec_path, lock_path):
    with open(spec_path) as file:
        spec = json.load(file)
    try:
        with open(lock_path) as file:
            lock = json.load(file)
    except FileNotFoundError:
        lock = {}

    # Modrinth's tag list is newest-first, which gives the ordering nix-minecraft's own (unordered)
    # game_locks.json can't.
    release_order = [tag["version"] for tag in get("/tag/game_version") if tag["version_type"] == "release"]
    available = set(spec["availableGameVersions"])

    invalid = [
        f"{name}.{slug}: {mod['channel']!r}"
        for name, world in spec["worlds"].items()
        for slug, mod in world["mods"].items()
        if mod["channel"] not in CHANNELS
    ]
    if invalid:
        sys.exit(f"invalid mod channel (expected one of {', '.join(CHANNELS)}): {'; '.join(invalid)}")

    new_lock = {
        name: resolve_world(name, world, available, release_order, lock.get(name, {}))
        for name, world in sorted(spec["worlds"].items())
    }

    for name, world in new_lock.items():
        old = lock.get(name, {"gameVersion": None, "mods": {}})
        if old["gameVersion"] != world["gameVersion"]:
            print(f"{name}: Minecraft {old['gameVersion']} -> {world['gameVersion']}")
        for slug, entry in world["mods"].items():
            old_version = old["mods"].get(slug, {}).get("version")
            if old_version != entry["version"]:
                print(f"{name}: {slug} {old_version} -> {entry['version']}")

    with open(lock_path, "w") as file:
        json.dump(new_lock, file, indent=2, sort_keys=True)
        file.write("\n")


if __name__ == "__main__":
    main(*sys.argv[1:])
