# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  den.aspects.harmony.nixos =
    {
      config,
      lib,
      modulesPath,
      ...
    }:
    {
      imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

      boot = {
        extraModulePackages = [ ];

        initrd = {
          availableKernelModules = [
            "xhci_pci"
            "ahci"
            "nvme"
            "usbhid"
            "sd_mod"
          ];

          kernelModules = [ ];
        };

        kernelModules = [ "kvm-intel" ];
      };

      fileSystems = {
        "/" = {
          device = "/dev/disk/by-uuid/d4c201a1-20a4-4b67-ac13-eeb7ed133a50";
          fsType = "ext4";
        };

        "/boot" = {
          options = [
            "fmask=0077"
            "dmask=0077"
          ];

          device = "/dev/disk/by-uuid/23DE-E9DA";
          fsType = "vfat";
        };
      };

      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      swapDevices = [ ];
    };
}
