{ inputs, my, ... }: {
  flake-file.inputs.nixos-hardware = {
    url = "github:NixOS/nixos-hardware";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  den.aspects.tensoon = {
    includes = with my; [
      (auto-upgrade { allowReboot = false; })
      (cachyos-kernel { })
      boot
      disko
      locale
      networkmanager
      noctalia
      noctalia-greeter
      pipewire
      preservation
      ssh-server
      umbriel
      yubikey
    ];

    nixos = { config, lib, ... }: {
      imports = [ (inputs.nixos-hardware.nixosModules.framework-intel-core-ultra-series3 or { }) ];
      # tensoon's /etc/ssh/ssh_host_ed25519_key.pub, generated by hand into /persist/etc/ssh/
      # during install. `agenix generate -a && agenix rekey -a` (YubiKey) rekeys against this and
      # writes secrets/rekeyed/tensoon* + secrets/rekeyed/tensoon-home-oscar*.
      age.rekey.hostPubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYa0oNYU887KosG7tsNrbTU8c49QiKaJdB1X6TWZyUh root@tensoon";

      # The PIXA3854 clickpad defaults to libinput's "button-areas" click method: a physical press
      # is a right-click only in the bottom-right corner, finger count ignored. Umbriel exposes no
      # click-method setting, so force "clickfinger" (1 finger = left, 2 = right, 3 = middle) at the
      # libinput layer. ModelAppleTouchpad is the only override that flips libinput's default; it
      # also drops the software button areas, which is the point. Matched by I2C vendor/product so
      # nothing else is touched. (GNOME hosts get clickfinger from Mutter and need no quirk.)
      environment.etc."libinput/local-overrides.quirks".text = ''
        [Framework 13 PIXA3854 clickpad - clickfinger]
        MatchUdevType=touchpad
        MatchBus=i2c
        MatchVendor=0x093A
        MatchProduct=0x1343
        ModelAppleTouchpad=1
      '';

      # proton-pass-agent (my.proton-pass) runs `pass-cli ssh-agent start`, and - like every
      # pass-cli subcommand - that creates a throwaway .session/pass-cli.db when there is no
      # session. pass-cli then won't rewrite the existing gnome-keyring key item on the next real
      # `pass-cli login` (its name is a fixed account hash), so the throwaway DB and the stored
      # key desync for good -> SQLCipher HMAC failure. Upstream makes it WantedBy=default.target,
      # so on this tmpfs-root host it fires every boot before a shell exists.
      #
      # Don't let default.target start the service. A .path unit watches for the real session
      # file (a no-session pass-cli.db has no session.json) and starts the service only once it
      # exists - so pass-cli is never run without a session, and, unlike a blocking ExecStartPre
      # guard, nothing stalls `nixos-rebuild switch` (HM activation waits on the units it starts).
      # On a normal boot session.json is already on /persist, so the agent still comes up at once.
      home-manager.users.oscar.systemd.user = {
        paths.proton-pass-agent = {
          Install.WantedBy = [ "default.target" ];
          Path.PathExists = "%h/.local/share/proton-pass-cli/.session/session.json";
          Unit.Description = "Start the Proton Pass agent once pass-cli has a session";
        };

        services.proton-pass-agent.Install.WantedBy = lib.mkForce [ ];
      };

      # The sudo "lecture" is shown once per user, tracked by a marker under /var/db/sudo that
      # this host's tmpfs root drops every boot - so it lectures on the first sudo after each
      # reboot. Turn it off.
      security.sudo.extraConfig = "Defaults lecture = never";

      services = {
        avahi = {
          enable = true;
          nssmdns4 = true;
        };

        printing.enable = true;
      };

      # This option defines the first version of NixOS you have installed on this particular machine, and is used to
      # maintain compatibility with application data (e.g. databases) created on older NixOS versions.
      #
      # Most users should NEVER change this value after the initial install, for any reason, even if you've upgraded
      # your system to a new NixOS release.
      #
      # This value does NOT affect the Nixpkgs version your packages and OS are pulled from, so changing it will NOT
      # upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how to actually do that.
      #
      # This value being lower than the current NixOS release does NOT mean your system is out of date, out of support,
      # or vulnerable.
      #
      # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
      # and migrated your data accordingly.
      #
      # For more information, see `man configuration.nix` or
      # https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
      #
      # Set during the initial install - confirm against `nixos-version` on the installer and match.
      system.stateVersion = "26.11";
      # `/` is tmpfs and `/etc/shadow` is not persisted, so a manual `passwd root` would be lost
      # on reboot. Give root the same declarative password as oscar (the age secret), so there's
      # always a working recovery login without persisting mutable user state.
      users.users.root.hashedPasswordFile = config.age.secrets.oscar-hashed-password.path;
    };

    # This value determines the Home Manager release that your configuration is compatible with. This helps avoid
    # breakage when a new Home Manager release introduces backwards incompatible changes.
    #
    # You can update Home Manager without changing this value. See the Home Manager release notes for a list of state
    # version changes in each release.
    provides =
      let
        # See the comment in OMARSHAL-M-T2QF.nix for why these sentinels are needed.
        hmSentinels = {
          hm64bit = { };
          hmAarch64 = { };
          hmDarwin = { };
          hmLinux = { };
        };
      in
      {
        oscar = hmSentinels // {
          homeManager.home.stateVersion = "26.11";
        };
      };
  };
}
