# A *client*-side aspect: makes this host offload builds to another host's Nix daemon over SSH
# (`nix.distributedBuilds`) - CPU offload to a beefier always-on machine, and/or building for a
# system this host can't natively execute derivations for (e.g. aarch64-darwin building
# x86_64-linux).
#
# The private half of the SSH keypair is a dedicated secret per builder (NOT the personal
# oscar-ssh-private-key, see oscar.nix) - remote build connections are made by the nix-daemon
# (root), not the interactive user, so the key has to be root-readable at daemon-start. The
# corresponding public key's `authorizedKeys` entry on the builder host is restricted to
# `nix-store --serve` only (see harmony.nix) so this secret can't be used for a general login.
#
# Usage:
#   includes = [ (remote-builder { builder = "harmony"; hostName = "harmony"; system = "x86_64-linux"; maxJobs = 32; publicHostKey = "..."; }) ];
#
# The keypair itself isn't generated by this aspect (agenix-rekey needs the YubiKey, which can't
# run unattended) - create it by hand once per builder:
#   ssh-keygen -t ed25519 -N "" -C "remote-builder@<builder>" -f /tmp/remote-builder-key
#   agenix edit secrets/remote-builder-<builder>-ssh-key.age   # paste the private key
#   agenix rekey -a
# then add the printed `.pub` (with a forced command) to the builder's authorizedKeys.
{
  my.remote-builder =
    {
      # Stable identifier for the secret filename - deliberately separate from `hostName` (the
      # address actually dialed), which can change (e.g. a LAN alias swapped for a MagicDNS name)
      # without that renaming/orphaning the secret and its already-rekeyed copies.
      builder,
      hostName,
      maxJobs,
      # base64 of `ssh-keyscan -t ed25519 <hostName>`'s output line (key + trailing newline) - same
      # shape nix.buildMachines.*.publicHostKey docs describe as `base64 -w0 ssh_host_*_key.pub`.
      # Pins the builder's host key here instead of relying on root's ~/.ssh/known_hosts.
      publicHostKey,
      system,
      speedFactor ? 1,
      sshUser ? "oscar",
      supportedFeatures ? [ ],
    }:
    let
      secretName = "remote-builder-${builder}-ssh-key";
    in
    {
      os = { config, ... }: {
        nix = {
          buildMachines = [
            {
              inherit
                hostName
                maxJobs
                publicHostKey
                speedFactor
                sshUser
                supportedFeatures
                system
                ;

              protocol = "ssh-ng";
              sshKey = config.age.secrets.${secretName}.path;
            }
          ];

          distributedBuilds = true;
        };
      };

      secrets.${secretName}.rekeyFile = ../../../secrets/${secretName}.age;
    };
}
